// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsL8CAuv2h2kzOVfc3EH_bbnTL_C_y6JI',
    appId: '1:497809288056:web:f60c0d61911d674c01768d',
    messagingSenderId: '497809288056',
    projectId: 'ivolunteerly',
    authDomain: 'ivolunteerly.firebaseapp.com',
    storageBucket: 'ivolunteerly.firebasestorage.app',
    measurementId: 'G-97NQQFYGHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFumnMAJNgTRXHWcCqepFjQh4tWK5TTwQ',
    appId: '1:497809288056:android:948ac20bdafaec0101768d',
    messagingSenderId: '497809288056',
    projectId: 'ivolunteerly',
    storageBucket: 'ivolunteerly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhgolS7bc7xI63FV8wHy_7j5jcMvG-w4',
    appId: '1:497809288056:ios:051814c0931c100401768d',
    messagingSenderId: '497809288056',
    projectId: 'ivolunteerly',
    storageBucket: 'ivolunteerly.firebasestorage.app',
    iosBundleId: 'com.ivolunteer.iVolunteerMobile',
  );
}
